"""Curated offline dictionary mapping common names and aliases to WinGet Package IDs.

Zero network required: the OfflineIntentCompiler resolves user tokens against
this table (exact match first, rapidfuzz typo tolerance second, dotted
WinGet-ID passthrough third). Keys are lowercase human-friendly names.
"""
from __future__ import annotations

WINGET_CATALOG: dict[str, str] = {
    # -- Browsers -------------------------------------------------------------
    "chrome": "Google.Chrome",
    "google chrome": "Google.Chrome",
    "firefox": "Mozilla.Firefox",
    "mozilla firefox": "Mozilla.Firefox",
    "firefox developer": "Mozilla.Firefox.DeveloperEdition",
    "brave": "Brave.Brave",
    "brave browser": "Brave.Brave",
    "edge": "Microsoft.Edge",
    "microsoft edge": "Microsoft.Edge",
    "zen": "Zen-Team.Zen-Browser",
    "zen browser": "Zen-Team.Zen-Browser",
    "opera": "Opera.Opera",
    "opera gx": "Opera.OperaGX",
    "vivaldi": "Vivaldi.Vivaldi",
    "arc": "TheBrowserCompany.Arc",
    "tor": "TorProject.TorBrowser",
    "tor browser": "TorProject.TorBrowser",

    # -- Editors & IDEs --------------------------------------------------------
    "vscode": "Microsoft.VisualStudioCode",
    "vs code": "Microsoft.VisualStudioCode",
    "visual studio code": "Microsoft.VisualStudioCode",
    "vscodium": "VSCodium.VSCodium",
    "neovim": "Neovim.Neovim",
    "nvim": "Neovim.Neovim",
    "vim": "vim.vim",
    "sublime": "SublimeHQ.SublimeText.4",
    "sublime text": "SublimeHQ.SublimeText.4",
    "sublime merge": "SublimeHQ.SublimeMerge",
    "notepad++": "Notepad++.Notepad++",
    "notepadplusplus": "Notepad++.Notepad++",
    "notepad plus plus": "Notepad++.Notepad++",
    "pycharm community": "JetBrains.PyCharm.Community",
    "pycharm": "JetBrains.PyCharm.Professional",
    "pycharm professional": "JetBrains.PyCharm.Professional",
    "intellij": "JetBrains.IntelliJIDEA.Community",
    "intellij idea": "JetBrains.IntelliJIDEA.Community",
    "intellij ultimate": "JetBrains.IntelliJIDEA.Ultimate",
    "webstorm": "JetBrains.WebStorm",
    "goland": "JetBrains.GoLand",
    "rider": "JetBrains.Rider",
    "clion": "JetBrains.CLion",
    "phpstorm": "JetBrains.PhpStorm",
    "rustrover": "JetBrains.RustRover",
    "cursor": "Anysphere.Cursor",
    "cursor editor": "Anysphere.Cursor",
    "zed": "Zed.Zed",
    "zed editor": "Zed.Zed",
    "visual studio": "Microsoft.VisualStudio.2022.Community",
    "visual studio 2022": "Microsoft.VisualStudio.2022.Community",
    "vs2022 community": "Microsoft.VisualStudio.2022.Community",
    "vs2022 professional": "Microsoft.VisualStudio.2022.Professional",
    "netbeans": "Apache.NetBeans",
    "eclipse": "EclipseFoundation.EclipseIDE",
    "lapce": "Lapce.Lapce",
    "helix": "Helix.Helix",
    "emacs": "GNU.Emacs",

    # -- Terminals & Shells -----------------------------------------------------
    "terminal": "Microsoft.WindowsTerminal",
    "windows terminal": "Microsoft.WindowsTerminal",
    "wt": "Microsoft.WindowsTerminal",
    "powershell": "Microsoft.PowerShell",
    "powershell 7": "Microsoft.PowerShell",
    "pwsh": "Microsoft.PowerShell",
    "git bash": "Git.Git",
    "alacritty": "Alacritty.Alacritty",
    "wezterm": "wez.wezterm",
    "hyper": "Zeit.Hyper",
    "starship": "Starship.Starship",
    "starship prompt": "Starship.Starship",
    "oh-my-posh": "JanDeDobbeleer.OhMyPosh",
    "oh my posh": "JanDeDobbeleer.OhMyPosh",
    "omp": "JanDeDobbeleer.OhMyPosh",
    "winfetch": "leetinces.WinFetch",
    "wsltty": "Mintty.WSLtty",

    # -- VCS, Runtimes & CLI tools ----------------------------------------------
    "git": "Git.Git",
    "gh": "GitHub.cli",
    "github": "GitHub.cli",
    "github cli": "GitHub.cli",
    "github desktop": "GitHub.GitHubDesktop",
    "git desktop": "GitHub.GitHubDesktop",
    "gitkraken": "Axosoft.GitKraken",
    "lazygit": "JesseDuffield.lazygit",
    "docker": "Docker.DockerDesktop",
    "docker desktop": "Docker.DockerDesktop",
    "rancher": "Rancher.RancherDesktop",
    "rancher desktop": "Rancher.RancherDesktop",
    "podman": "RedHat.Podman",
    "podman desktop": "RedHat.Podman-Desktop",
    "nodejs": "OpenJS.NodeJS",
    "node": "OpenJS.NodeJS",
    "node.js": "OpenJS.NodeJS",
    "node lts": "OpenJS.NodeJS.LTS",
    "nodejs lts": "OpenJS.NodeJS.LTS",
    "deno": "DenoLand.Deno",
    "bun": "Oven-sh.Bun",
    "python": "Python.Python.3.12",
    "python3": "Python.Python.3.12",
    "python 3.12": "Python.Python.3.12",
    "python 3.11": "Python.Python.3.11",
    "python 3.13": "Python.Python.3.13",
    "uv": "astral-sh.uv",
    "pipx": "pipx.pipx",
    "poetry": "Python.Poetry",
    "rust": "Rustlang.Rustup",
    "rustup": "Rustlang.Rustup",
    "rust lang": "Rustlang.Rustup",
    "golang": "GoLang.Go",
    "go": "GoLang.Go",
    "go lang": "GoLang.Go",
    "dotnet": "Microsoft.DotNet.SDK.8",
    "dotnet 8": "Microsoft.DotNet.SDK.8",
    "dotnet sdk 8": "Microsoft.DotNet.SDK.8",
    "dotnet 9": "Microsoft.DotNet.SDK.9",
    "dotnet sdk 9": "Microsoft.DotNet.SDK.9",
    "java 21": "Microsoft.OpenJDK.21",
    "openjdk 21": "Microsoft.OpenJDK.21",
    "temurin 21": "EclipseAdoptium.Temurin.21.JDK",
    "temurin 17": "EclipseAdoptium.Temurin.17.JDK",
    "maven": "Apache.Maven",
    "gradle": "Gradle.Gradle",
    "ripgrep": "BurntSushi.ripgrep.MSVC",
    "rg": "BurntSushi.ripgrep.MSVC",
    "fzf": "junegunn.fzf",
    "bat": "sharkdp.bat",
    "bat cat": "sharkdp.bat",
    "fd": "sharkdp.fd",
    "fd find": "sharkdp.fd",
    "eza": "eza-community.eza",
    "zoxide": "ajeetdsouza.zoxide",
    "jq": "jqlang.jq",
    "yq": "MikeFarah.yq",
    "wget": "JernejSimoncic.Wget",
    "curl": "cURL.cURL",
    "make": "GnuWin32.Make",
    "cmake": "Kitware.CMake",
    "ninja": "Ninja-build.Ninja",
    "llvm": "LLVM.LLVM",
    "mingw": "niXman.mingw",
    "msys2": "MSYS2.MSYS2",
    "perl": "StrawberryPerl.StrawberryPerl",
    "php": "PHP.PHP.8.3",
    "ruby": "RubyInstallerTeam.Ruby.3.3",
    "lua": "Lua.Lua",
    "zig": "zig.zig",
    "kubectl": "Kubernetes.kubectl",
    "minikube": "Kubernetes.minikube",
    "kind": "Kubernetes.kind",
    "helm": "Helm.Helm",
    "terraform": "HashiCorp.Terraform",
    "packer": "HashiCorp.Packer",
    "pulumi": "Pulumi.Pulumi",
    "aws cli": "Amazon.AWSCLI",
    "awscli": "Amazon.AWSCLI",
    "azure cli": "Microsoft.AzureCLI",
    "az cli": "Microsoft.AzureCLI",
    "gcloud": "Google.CloudSDK",
    "google cloud sdk": "Google.CloudSDK",
    "doctl": "DigitalOcean.doctl",
    "flyctl": "superfly.flyctl",
    "supabase": "supabase.supabase",
    "turso": "Turso.Turso",
    "postman": "Postman.Postman",
    "insomnia": "Kong.Insomnia",
    "bruno": "Bruno.Bruno",
    "httpie": "HTTPie.HTTPie",

    # -- Databases & data tools ---------------------------------------------------
    "postgres": "PostgreSQL.PostgreSQL.17",
    "postgresql": "PostgreSQL.PostgreSQL.17",
    "pgadmin": "pgAdmin.pgAdmin",
    "dbeaver": "DBeaver.DBeaver",
    "mongodb compass": "MongoDB.Compass",
    "compass": "MongoDB.Compass",
    "redis insight": "Redis.RedisInsight",
    "tableplus": "TablePlus.TablePlus",
    "beekeeper": "BeekeeperStudio.BeekeeperStudio",

    # -- Utilities & compression ----------------------------------------------------
    "7zip": "7zip.7zip",
    "7-zip": "7zip.7zip",
    "7 zip": "7zip.7zip",
    "peazip": "Giorgiotani.Peazip",
    "winrar": "RARLab.WinRAR",
    "powertoys": "Microsoft.PowerToys",
    "everything": "voidtools.Everything",
    "everything search": "voidtools.Everything",
    "fastcopy": "SHIRouZU.FastCopy",
    "bleachbit": "BleachBit.BleachBit",
    "rufus": "Rufus.Rufus",
    "ventoy": "Ventoy.Ventoy",
    "wiztree": "AntibodySoftware.WizTree",
    "windirstat": "WinDirStat.WinDirStat",
    "sharex": "ShareX.ShareX",
    "greenshot": "Greenshot.Greenshot",
    "snipaste": "Snipaste.Snipaste",
    "eartrumpet": "File-New-Project.EarTrumpet",
    "translucenttb": "TranslucentTB.TranslucentTB",
    "autohotkey": "AutoHotkey.AutoHotkey",
    "auto hotkey": "AutoHotkey.AutoHotkey",
    "ahk": "AutoHotkey.AutoHotkey",
    "ditto": "Ditto.Ditto",
    "qlipper": "Qlipper.Qlipper",
    "keepass": "DominikReichl.KeePass",
    "keepassxc": "KeePassXCTeam.KeePassXC",
    "bitwarden": "Bitwarden.Bitwarden",
    "1password": "AgileBits.1Password",
    "protonvpn": "Proton.ProtonVPN",
    "proton vpn": "Proton.ProtonVPN",
    "windscribe": "Windscribe.Windscribe",
    "tailscale": "Tailscale.Tailscale",
    "wireguard": "WireGuard.WireGuard",
    "syncthing": "Syncthing.Syncthing",

    # -- Media, chat & everyday apps --------------------------------------------------
    "vlc": "VideoLAN.VLC",
    "vlc media player": "VideoLAN.VLC",
    "spotify": "Spotify.Spotify",
    "discord": "Discord.Discord",
    "slack": "SlackTechnologies.Slack",
    "telegram": "Telegram.TelegramDesktop",
    "signal": "OpenWhisperSystems.Signal",
    "whatsapp": "Meta.WhatsApp",
    "zoom": "Zoom.Zoom",
    "teams": "Microsoft.Teams",
    "obs": "OBSProject.OBSStudio",
    "obs studio": "OBSProject.OBSStudio",
    "notion": "Notion.Notion",
    "obsidian": "Obsidian.Obsidian",
    "logseq": "Logseq.Logseq",
    "anytype": "Anytype.Anytype",
    "anki": "Anki.Anki",
    "calibre": "calibre.calibre",
    "sumatrapdf": "SumatraPDF.SumatraPDF",
    "sumatra": "SumatraPDF.SumatraPDF",
    "krita": "KDE.Krita",
    "gimp": "GIMP.GIMP",
    "blender": "BlenderFoundation.Blender",
    "inkscape": "Inkscape.Inkscape",
    "figma": "Figma.Figma",
    "handbrake": "HandBrake.HandBrake",
    "kdenlive": "KDE.Kdenlive",
    "audacity": "Audacity.Audacity",
    "foobar": "PeterPawlowski.foobar2000",
    "foobar2000": "PeterPawlowski.foobar2000",
    "mpv": "mpv.mpv",
    "stremio": "Stremio.Stremio",
    "qbittorrent": "qBittorrent.qBittorrent",
    "thunderbird": "Mozilla.Thunderbird",
    "protonmail": "Proton.ProtonMail",
    "steam": "Valve.Steam",
    "epic games": "EpicGames.EpicGamesLauncher",
    "gog": "GOG.Galaxy",
    "gog galaxy": "GOG.Galaxy",
    "prismlauncher": "PrismLauncher.PrismLauncher",
    "minecraft launcher": "Mojang.MinecraftLauncher",
}


def catalog_size() -> int:
    """Number of alias keys in the offline catalog."""
    return len(WINGET_CATALOG)


def lookup(name: str) -> str | None:
    """Exact, case-insensitive lookup. Returns the WinGet ID or None."""
    if not name:
        return None
    return WINGET_CATALOG.get(name.strip().lower())
